const taskData = [
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'prune',
    month: 'January',
  },
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'prune',
    month: 'February',
  },
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'prune',
    month: 'March',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'prune',
    month: 'January',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'prune',
    month: 'February',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'prune',
    month: 'March',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'prune',
    month: 'January',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'prune',
    month: 'February',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'prune',
    month: 'March',
  },
  {
    crop: 'Apple',
    week: '2',
    task: 'plant trees',
    month: 'January',
  },
  {
    crop: 'Apple',
    week: '2',
    task: 'prune trees',
    month: 'January',
  },
  {
    crop: 'Shallot',
    week: '1',
    task: 'plant sets in 8cm pots in protected position',
    month: 'January',
  },
  {
    crop: 'Leek',
    week: '4',
    task: 'sow seed under glass / indoors',
    month: 'January',
  },
  {
    crop: 'Onion Seed',
    week: '4',
    task: 'sow under glass / indoors',
    month: 'January',
  },
  {
    crop: 'Cauliflower',
    week: '4',
    task: 'sow seed indoors',
    month: 'January',
  },
  {
    crop: 'Apple',
    week: '2',
    task: 'plant trees',
    month: 'February',
  },
  {
    crop: 'Apple',
    week: '2',
    task: 'prune trees',
    month: 'February',
  },
  {
    crop: 'Broccoli',
    week: '1',
    task: 'begin harvest',
    month: 'February',
  },
  {
    crop: 'Broad Beans',
    week: '2',
    task: 'sow seeds in pots for spring planting',
    month: 'February',
  },
  {
    crop: 'Cauliflower',
    week: '2',
    task: 'prepare ground',
    month: 'February',
  },
  {
    crop: 'Cauliflower',
    week: '2',
    task: 'prepare ground',
    month: 'February',
  },
  {
    crop: 'Celery',
    week: '2',
    task: 'sow seeds indoors',
    month: 'February',
  },
  {
    crop: 'Broccoli',
    week: '3',
    task: 'begin harvest',
    month: 'February',
  },
  {
    crop: 'Sweet pepper',
    week: '3',
    task: 'sow seeds',
    month: 'February',
  },
  {
    crop: 'mangetout',
    week: '3',
    task: 'sow early types under cloches',
    month: 'February',
  },
  {
    crop: 'Asparagus',
    week: '4',
    task: 'sow seeds inside',
    month: 'February',
  },
  {
    crop: 'Broad Beans',
    week: '4',
    task: 'sow seeds outside in spring',
    month: 'February',
  },
  {
    crop: 'Carrot',
    week: '4',
    task: 'sow seed of early varieties under cloches',
    month: 'February',
  },
  {
    crop: 'Garlic',
    week: '4',
    task: 'plant in late winter / spring',
    month: 'February',
  },
  {
    crop: 'Leek',
    week: '4',
    task: 'thin seedlings sown in containers',
    month: 'February',
  },
  {
    crop: 'Apple',
    week: '2',
    task: 'plant trees',
    month: 'March',
  },
  {
    crop: 'Apple',
    week: '2',
    task: 'prune trees',
    month: 'March',
  },
  {
    crop: 'mangetout',
    week: '1',
    task: 'start to sow seeds of early types outdoors',
    month: 'March',
  },
  {
    crop: 'Rhubarb',
    week: '1',
    task: 'start to harvest',
    month: 'March',
  },
  {
    crop: 'Tomatoes',
    week: '1',
    task: 'sow seed inside',
    month: 'March',
  },
  {
    crop: 'Brussels Sprouts',
    week: '1',
    task: 'sow seed of early varieties',
    month: 'March',
  },
  {
    crop: 'pumpkin',
    week: '1',
    task: 'prepare soil',
    month: 'March',
  },
  {
    crop: 'Asparagus',
    week: '2',
    task: 'apply spring fertiliser',
    month: 'March',
  },
  {
    crop: 'Beetroot',
    week: '2',
    task: 'sow seeds under cloches',
    month: 'March',
  },
  {
    crop: 'Broad Beans',
    week: '2',
    task: 'transplant pot grown plants to open ground',
    month: 'March',
  },
  {
    crop: 'Cauliflower',
    week: '2',
    task: 'harden off',
    month: 'March',
  },
  {
    crop: 'Jerusalem Artichoke',
    week: '2',
    task: 'plant tubers',
    month: 'March',
  },
  {
    crop: 'Kohlrabi',
    week: '2',
    task: 'sow seeds indoors',
    month: 'March',
  },
  {
    crop: 'Onion',
    week: '2',
    task: 'sow seed outdoors',
    month: 'March',
  },
  {
    crop: 'Spring Onion',
    week: '2',
    task: 'start to sow fortnightly',
    month: 'March',
  },
  {
    crop: 'Potatoes',
    week: '2',
    task: 'plant out sprouted sets',
    month: 'March',
  },
  {
    crop: 'mangetout',
    week: '2',
    task: 'sow maincrop seeds outdoors',
    month: 'March',
  },
  {
    crop: 'Spinach',
    week: '2',
    task: 'sow seed outside',
    month: 'March',
  },
  {
    crop: 'Brussels Sprouts',
    week: '3',
    task: 'thin seedlings as they appear',
    month: 'March',
  },
  {
    crop: 'Cauliflower',
    week: '3',
    task: 'plant out',
    month: 'March',
  },
  {
    crop: 'Lettuce',
    week: '3',
    task: 'start sowing seed outside every two weeks',
    month: 'March',
  },
  {
    crop: 'Mustard',
    week: '3',
    task: 'sow seed outdoors for seeds',
    month: 'March',
  },
  {
    crop: 'Onion Sets',
    week: '3',
    task: 'plant',
    month: 'March',
  },
  {
    crop: 'Onion Sets',
    week: '3',
    task: 'protect from birds for 5 weeks',
    month: 'March',
  },
  {
    crop: 'Radish',
    week: '3',
    task: 'sow seed under cloches',
    month: 'March',
  },
  {
    crop: 'Shallot',
    week: '3',
    task: 'plant sets outside (18cm / 7in apart)',
    month: 'March',
  },
  {
    crop: 'Shallot',
    week: '3',
    task: 'protect from birds for 5 weeks',
    month: 'March',
  },
  {
    crop: 'Sweet Pepper',
    week: '3',
    task: 'pot up',
    month: 'March',
  },
  {
    crop: 'Asparagus',
    week: '4',
    task: 'plant outside',
    month: 'March',
  },
  {
    crop: 'Beetroot',
    week: '4',
    task: 'sow seed in pots indoors',
    month: 'March',
  },
  {
    crop: 'Brussels Sprouts',
    week: '4',
    task: 'Sow seed of mid to late varieties',
    month: 'March',
  },
  {
    crop: 'Cabbage',
    week: '4',
    task: 'sow seeds indoors',
    month: 'March',
  },
  {
    crop: 'Carrot',
    week: '4',
    task: 'remove cloches from early sown varieties',
    month: 'March',
  },
  {
    crop: 'Carrot',
    week: '4',
    task: 'sow early seed varieties in open',
    month: 'March',
  },
  {
    crop: 'Kohlrabi',
    week: '4',
    task: 'sow seeds outside',
    month: 'March',
  },
  {
    crop: 'Spinach',
    week: '4',
    task: 'sow seed inside',
    month: 'March',
  },
  {
    crop: 'pumpkin',
    week: '4',
    task: 'sow seed indoors',
    month: 'March',
  },
  {
    crop: 'Swiss Chard',
    week: '4',
    task: 'sow outdoors with cloche protection',
    month: 'March',
  },
  {
    crop: 'Turnip',
    week: '4',
    task: 'start to sow seed outdoors',
    month: 'March',
  },
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'mulch',
    month: 'April',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'mulch',
    month: 'April',
  },
  {
    crop: 'Peach',
    week: '2',
    task: 'protect blossom from frost',
    month: 'April',
  },
  {
    crop: 'Peach',
    week: '2',
    task: 'spring prune after blossoms fade',
    month: 'April',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'mulch',
    month: 'April',
  },
  {
    crop: 'Broccoli',
    week: '1',
    task: 'sow under cover',
    month: 'April',
  },
  {
    crop: 'Leek',
    week: '1',
    task: 'sow seed outside in a temporary seed bed',
    month: 'April',
  },
  {
    crop: 'Onion seeds',
    week: '1',
    task: 'harden off seedlings',
    month: 'April',
  },
  {
    crop: 'Radish',
    week: '1',
    task: 'sow seed outside',
    month: 'April',
  },
  {
    crop: 'Salsify',
    week: '1',
    task: 'sow seeds',
    month: 'April',
  },
  {
    crop: 'Tomatoes',
    week: '1',
    task: 'pot-up young plants',
    month: 'April',
  },
  {
    crop: 'Beetroot',
    week: '2',
    task: 'sow seed outside',
    month: 'April',
  },
  {
    crop: 'Broccoli',
    week: '2',
    task: 'sow seed bed',
    month: 'April',
  },
  {
    crop: 'Cabbage',
    week: '2',
    task: 'sow outdoors',
    month: 'April',
  },
  {
    crop: 'Calabrese',
    week: '2',
    task: 'sow seed',
    month: 'April',
  },
  {
    crop: 'Cauliflower',
    week: '2',
    task: 'weekly feed',
    month: 'April',
  },
  {
    crop: 'Courgette',
    week: '2',
    task: 'sow seeds indoors',
    month: 'April',
  },
  {
    crop: 'Cucumber',
    week: '2',
    task: 'sow seeds indoors',
    month: 'April',
  },
  {
    crop: 'Kohlrabi',
    week: '2',
    task: 'harden off seedlings',
    month: 'April',
  },
  {
    crop: 'Lettuce',
    week: '2',
    task: 'begin to thin seedlings, distance by variety',
    month: 'April',
  },
  {
    crop: 'Sweetcorn',
    week: '2',
    task: 'sow seed indoors / greenhouse',
    month: 'April',
  },
  {
    crop: 'Swiss Chard',
    week: '2',
    task: 'sow seed outdoors no protection',
    month: 'April',
  },
  {
    crop: 'Broccoli',
    week: '3',
    task: 'sow under cover',
    month: 'April',
  },
  {
    crop: 'Celery',
    week: '3',
    task: 'plant out',
    month: 'April',
  },
  {
    crop: 'Spinach',
    week: '3',
    task: 'plant out seed sown indoors',
    month: 'April',
  },
  {
    crop: 'Spinach',
    week: '3',
    task: 'Thin out previously sown seedlings',
    month: 'April',
  },
  {
    crop: 'Kohlrabi',
    week: '3',
    task: 'plant out in final position',
    month: 'April',
  },
  {
    crop: 'Leek',
    week: '3',
    task: 'harden off container grown seedlings',
    month: 'April',
  },
  {
    crop: 'Parsnip',
    week: '3',
    task: 'sow seed outside',
    month: 'April',
  },
  {
    crop: 'Sweetcorn',
    week: '3',
    task: 'sow seed under cloches',
    month: 'April',
  },
  {
    crop: 'French Beans',
    week: '3',
    task: 'sow seeds under cloches',
    month: 'April',
  },
  {
    crop: 'French Beans',
    week: '3',
    task: 'sow seeds in pots indoors',
    month: 'April',
  },
  {
    crop: 'Onion',
    week: '3',
    task: 'plant out seedlings',
    month: 'April',
  },
  {
    crop: 'Runner Beans',
    week: '3',
    task: 'sow seed under cloches',
    month: 'April',
  },
  {
    crop: 'Turnip',
    week: '3',
    task: 'thin seedlings 15cm earlies, 25cm maincrops',
    month: 'April',
  },
  {
    crop: 'Beetroot',
    week: '4',
    task: 'plant out seedlings sown in pots indoors',
    month: 'April',
  },
  {
    crop: 'Broccoli',
    week: '4',
    task: 'sow seed bed',
    month: 'April',
  },
  {
    crop: 'Cabbage',
    week: '4',
    task: 'Plant out indoor sown plants',
    month: 'April',
  },
  {
    crop: 'Carrot',
    week: '4',
    task: 'sow maincrop seed',
    month: 'April',
  },
  {
    crop: 'Cucumber',
    week: '4',
    task: 'sow seed under cloches outside',
    month: 'April',
  },
  {
    crop: 'Kale (curly)',
    week: '4',
    task: 'sow in pots or seed bed',
    month: 'April',
  },
  {
    crop: 'Runner Beans',
    week: '4',
    task: 'sow seed in pots indoors',
    month: 'April',
  },
  {
    crop: 'Potatoes',
    week: '4',
    task: 'nitrogen feed fortnightly',
    month: 'April',
  },
  {
    crop: 'pumpkin',
    week: '4',
    task: 'harden off',
    month: 'April',
  },
  {
    crop: 'Tomatoes',
    week: '4',
    task: 'begin to harden off',
    month: 'April',
  },
  {
    crop: 'Beetroot',
    week: '1',
    task: 'thin out seedlings',
    month: 'May',
  },
  {
    crop: 'French Beans',
    week: '1',
    task: 'sow seed outside',
    month: 'May',
  },
  {
    crop: 'French Beans',
    week: '1',
    task: 'harden off seedlings',
    month: 'May',
  },
  {
    crop: 'Jerusalem Artichoke',
    week: '1',
    task: 'erect supports',
    month: 'May',
  },
  {
    crop: 'Leek',
    week: '1',
    task: 'transplant container grown seedlings to final position',
    month: 'May',
  },
  {
    crop: 'Leek',
    week: '1',
    task: 'thin seedlings from seeds sown outdoors',
    month: 'May',
  },
  {
    crop: 'Rhubarb',
    week: '1',
    task: 'apply mulch',
    month: 'May',
  },
  {
    crop: 'Strawberries',
    week: '1',
    task: 'mulch around plants',
    month: 'May',
  },
  {
    crop: 'pumpkin',
    week: '1',
    task: 'plant out',
    month: 'May',
  },
  {
    crop: 'Brussels Sprouts',
    week: '2',
    task: 'transplant',
    month: 'May',
  },
  {
    crop: 'Cauliflower',
    week: '2',
    task: 'sow seed in pots',
    month: 'May',
  },
  {
    crop: 'Courgette',
    week: '2',
    task: 'Harden off indoor grown plants',
    month: 'May',
  },
  {
    crop: 'Cucumber',
    week: '2',
    task: 'Harden off indoor grown plants',
    month: 'May',
  },
  {
    crop: 'French Beans',
    week: '2',
    task: 'plant out seedlings sown in pots indoors',
    month: 'May',
  },
  {
    crop: 'Sweetcorn',
    week: '2',
    task: 'plant out seedlings sown in pots indoors',
    month: 'May',
  },
  {
    crop: 'Swiss Chard',
    week: '2',
    task: 'thin out seedlings',
    month: 'May',
  },
  {
    crop: 'Radish',
    week: '2',
    task: 'begin to harvest',
    month: 'May',
  },
  {
    crop: 'Runner Beans',
    week: '2',
    task: 'harden off seedlings',
    month: 'May',
  },
  {
    crop: 'Cabbage',
    week: '3',
    task: 'harvest',
    month: 'May',
  },
  {
    crop: 'Courgette',
    week: '3',
    task: 'plant out',
    month: 'May',
  },
  {
    crop: 'Leek',
    week: '3',
    task: 'buy seedlings and plant outside',
    month: 'May',
  },
  {
    crop: 'Onion',
    week: '3',
    task: 'water in dry conditions',
    month: 'May',
  },
  {
    crop: 'Parsnip',
    week: '3',
    task: 'thin seedlings to 15cm / 6in apart',
    month: 'May',
  },
  {
    crop: 'mangetout',
    week: '3',
    task: 'Harvest early types started off under cloches',
    month: 'May',
  },
  {
    crop: 'Tomatoes',
    week: '3',
    task: 'plant out',
    month: 'May',
  },
  {
    crop: 'Runner Beans',
    week: '3',
    task: 'sow seed outside',
    month: 'May',
  },
  {
    crop: 'Runner Beans',
    week: '3',
    task: 'plant out seedlings sown in pots indoors',
    month: 'May',
  },
  {
    crop: 'Shallot',
    week: '3',
    task: 'water in dry conditions',
    month: 'May',
  },
  {
    crop: 'Asparagus',
    week: '4',
    task: 'stop harvesting',
    month: 'May',
  },
  {
    crop: 'Broad Beans',
    week: '4',
    task: 'begin to harvest',
    month: 'May',
  },
  {
    crop: 'Carrot',
    week: '4',
    task: 'harvest those sown under cloches',
    month: 'May',
  },
  {
    crop: 'Cucumber',
    week: '4',
    task: 'plant out (grown indoors / shop bought)',
    month: 'May',
  },
  {
    crop: 'Leek',
    week: '4',
    task: 'transplant spring sown seedlings to final position',
    month: 'May',
  },
  {
    crop: 'Lettuce',
    week: '4',
    task: 'begin to harvest',
    month: 'May',
  },
  {
    crop: 'mangetout',
    week: '4',
    task: 'harvest early types sown outdoors',
    month: 'May',
  },
  {
    crop: 'Potatoes',
    week: '4',
    task: 'potash feed fortnightly',
    month: 'May',
  },
  {
    crop: 'Swede',
    week: '4',
    task: 'sow seed outdoors',
    month: 'May',
  },
  {
    crop: 'Sweet Pepper',
    week: '4',
    task: 'harden off',
    month: 'May',
  },
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'water',
    month: 'June',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'water',
    month: 'June',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'water',
    month: 'June',
  },
  {
    crop: 'Cauliflower',
    week: '1',
    task: 'begin to harvest',
    month: 'June',
  },
  {
    crop: 'Kale (curly)',
    week: '1',
    task: 'transplant to final position',
    month: 'June',
  },
  {
    crop: 'Sweet Pepper',
    week: '1',
    task: 'move to final position',
    month: 'June',
  },
  {
    crop: 'Turnip',
    week: '1',
    task: 'begin to  harvest',
    month: 'June',
  },
  {
    crop: 'Spinach',
    week: '2',
    task: 'havest spring grown leaves',
    month: 'June',
  },
  {
    crop: 'Carrot',
    week: '2',
    task: 'harvest as they become ready',
    month: 'June',
  },
  {
    crop: 'Cauliflower',
    week: '2',
    task: 'plant outside',
    month: 'June',
  },
  {
    crop: 'Cucumber',
    week: '2',
    task: 'prune main stem',
    month: 'June',
  },
  {
    crop: 'Cauliflower',
    week: '3',
    task: 'begin weekly feed',
    month: 'June',
  },
  {
    crop: 'Swede',
    week: '3',
    task: 'thin seedlings in stages to 25cm apart',
    month: 'June',
  },
  {
    crop: 'Broccoli',
    week: '4',
    task: 'plant final position',
    month: 'June',
  },
  {
    crop: 'Shallot',
    week: '4',
    task: 'Harvest some for immediate use',
    month: 'June',
  },
  {
    crop: 'Shallot',
    week: '3',
    task: 'stop watering',
    month: 'June',
  },
  {
    crop: 'Swiss Chard',
    week: '4',
    task: 'begin to harvest',
    month: 'June',
  },
  {
    crop: 'Broccoli',
    week: '1',
    task: 'plant final position',
    month: 'July',
  },
  {
    crop: 'Broccoli',
    week: '1',
    task: 'plant final position',
    month: 'July',
  },
  {
    crop: 'Courgette',
    week: '1',
    task: 'begin to harvest',
    month: 'July',
  },
  {
    crop: 'Kale (rape)',
    week: '1',
    task: 'sow in final position',
    month: 'July',
  },
  {
    crop: 'Mustard',
    week: '1',
    task: 'harvest seeds',
    month: 'July',
  },
  {
    crop: 'Beetroot',
    week: '2',
    task: 'begin to harvest',
    month: 'July',
  },
  {
    crop: 'Broccoli',
    week: '2',
    task: 'plant final position',
    month: 'July',
  },
  {
    crop: 'Cucumber',
    week: '2',
    task: 'begin to harvest',
    month: 'July',
  },
  {
    crop: 'Jerusalem Artichoke',
    week: '2',
    task: 'cut stem to 1.5m high',
    month: 'July',
  },
  {
    crop: 'Onion',
    week: '2',
    task: 'stop watering',
    month: 'July',
  },
  {
    crop: 'mangetout',
    week: '2',
    task: 'harvest',
    month: 'July',
  },
  {
    crop: 'Potatoes',
    week: '2',
    task: 'plant sets for autumn harvest',
    month: 'July',
  },
  {
    crop: 'Shallot',
    week: '2',
    task: 'harvest / dry out for storage',
    month: 'July',
  },
  {
    crop: 'Sweetcorn',
    week: '3',
    task: 'begin to harvest',
    month: 'July',
  },
  {
    crop: 'French Beans',
    week: '3',
    task: 'begin to harvest',
    month: 'July',
  },
  {
    crop: 'Cabbage',
    week: '4',
    task: 'sow (pots / temporary bed)',
    month: 'July',
  },
  {
    crop: 'Celery',
    week: '4',
    task: 'begin to harvest',
    month: 'July',
  },
  {
    crop: 'Onion',
    week: '4',
    task: 'begin to harvest',
    month: 'July',
  },
  {
    crop: 'Garlic',
    week: '4',
    task: 'begin to harvest',
    month: 'July',
  },
  {
    crop: 'Kohlrabi',
    week: '1',
    task: 'sow seed for autumn crop',
    month: 'August',
  },
  {
    crop: 'French Beans',
    week: '1',
    task: 'begin to harvest climbing / pole varieties',
    month: 'August',
  },
  {
    crop: 'Runner Beans',
    week: '1',
    task: 'begin to harvest',
    month: 'August',
  },
  {
    crop: 'Calabrese',
    week: '2',
    task: 'harvest ',
    month: 'August',
  },
  {
    crop: 'Leek',
    week: '2',
    task: 'begin to earth up strong growing plants',
    month: 'August',
  },
  {
    crop: 'Raspberries',
    week: '2',
    task: 'prune',
    month: 'August',
  },
  {
    crop: 'Leek',
    week: '3',
    task: 'continue earthing up',
    month: 'August',
  },
  {
    crop: 'Cabbage',
    week: '4',
    task: 'begin to harvest',
    month: 'August',
  },
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'take cuttings',
    month: 'September',
  },
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'take cuttings',
    month: 'October',
  },
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'take cuttings',
    month: 'November',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'take cuttings',
    month: 'September',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'take cuttings',
    month: 'October',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'take cuttings',
    month: 'November',
  },
  {
    crop: 'Peach',
    week: '2',
    task: 'autumn prune after harvest',
    month: 'September',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'take cuttings',
    month: 'September',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'take cuttings',
    month: 'October',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'take cuttings',
    month: 'November',
  },
  {
    crop: 'Parsnip',
    week: '2',
    task: 'begin to harvest',
    month: 'September',
  },
  {
    crop: 'Jerusalem Artichoke',
    week: '3',
    task: 'cut stem to 15cm high',
    month: 'September',
  },
  {
    crop: 'Spinach',
    week: '3',
    task: 'sow in autumn',
    month: 'September',
  },
  {
    crop: 'Swede',
    week: '3',
    task: 'begin to harvest  (through to early Jan)',
    month: 'September',
  },
  {
    crop: 'Cabbage',
    week: '2',
    task: 'transplant',
    month: 'September',
  },
  {
    crop: 'Asparagus',
    week: '2',
    task: 'cut down when foliage yellows',
    month: 'October',
  },
  {
    crop: 'Salsify',
    week: '1',
    task: 'begin to harvest',
    month: 'October',
  },
  {
    crop: 'Blackberries',
    week: '2',
    task: 'prune when fruting is complete',
    month: 'October',
  },
  {
    crop: 'Cauliflower',
    week: '2',
    task: 'begin to harvest',
    month: 'October',
  },
  {
    crop: 'pumpkin',
    week: '2',
    task: 'take indoors to cure',
    month: 'October',
  },
  {
    crop: 'Kale',
    week: '3',
    task: 'begin to harvest',
    month: 'October',
  },
  {
    crop: 'Leek',
    week: '3',
    task: 'begin to harvest',
    month: 'October',
  },
  {
    crop: 'Strawberries',
    week: '3',
    task: 'buy runners',
    month: 'October',
  },
  {
    crop: 'Peach',
    week: '2',
    task: 'plant bare-rooted trees',
    month: 'November',
  },
  {
    crop: 'Broad Beans',
    week: '1',
    task: 'sow seeds outside for an early crop',
    month: 'November',
  },
  {
    crop: 'Jerusalem Artichoke',
    week: '1',
    task: 'harvest into late winter',
    month: 'November',
  },
  {
    crop: 'Spinach',
    week: '1',
    task: 'begin to harvest',
    month: 'November',
  },
  {
    crop: 'Rhubarb',
    week: '1',
    task: 'plant crowns up to end of February',
    month: 'November',
  },
  {
    crop: 'pumpkin',
    week: '1',
    task: 'start to use',
    month: 'November',
  },
  {
    crop: 'Brussels Sprouts',
    week: '2',
    task: 'begin to harvest',
    month: 'November',
  },
  {
    crop: 'Plum',
    week: '4',
    task: 'plant trees from now to early March',
    month: 'November',
  },
  {
    crop: 'Apple',
    week: '2',
    task: 'plant trees',
    month: 'December',
  },
  {
    crop: 'Apple',
    week: '2',
    task: 'prune trees',
    month: 'December',
  },
  {
    crop: 'Garlic',
    week: '1',
    task: 'autumn planting',
    month: 'December',
  },
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'buy and plant (up to end February)',
    month: 'December',
  },
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'buy and plant (up to end February)',
    month: 'January',
  },
  {
    crop: 'Blackcurrant',
    week: '2',
    task: 'buy and plant (up to end February)',
    month: 'February',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'buy and plant (up to end February)',
    month: 'December',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'buy and plant (up to end February)',
    month: 'January',
  },
  {
    crop: 'Gooseberry',
    week: '2',
    task: 'buy and plant (up to end February)',
    month: 'February',
  },
  {
    crop: 'Raspberries',
    week: '2',
    task: 'buy and plant (up to end February)',
    month: 'December',
  },
  {
    crop: 'Raspberries',
    week: '2',
    task: 'buy and plant (up to end February)',
    month: 'January',
  },
  {
    crop: 'Raspberries',
    week: '2',
    task: 'buy and plant (up to end February)',
    month: 'February',
  },
  {
    crop: 'Raspberries',
    week: '2',
    task: 'prune',
    month: 'December',
  },
  {
    crop: 'Raspberries',
    week: '2',
    task: 'prune',
    month: 'January',
  },
  {
    crop: 'Raspberries',
    week: '2',
    task: 'prune',
    month: 'February',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'buy and plant',
    month: 'December',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'buy and plant',
    month: 'January',
  },
  {
    crop: 'whitecurrant',
    week: '2',
    task: 'buy and plant',
    month: 'February',
  },
];

module.exports = { taskData };
